name: Go

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.17
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Run tests and generate coverage report
        run: go test -race -coverprofile cover.out -covermode atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./cover.out
